# Generated by Django 3.2.4 on 2021-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'DEPOSIT'), ('W', 'WITHDRAWAL'), ('T', 'WIRE_TRANSFER')], max_length=1),
        ),
    ]
