# Generated by Django 3.2.4 on 2021-06-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='Currency_iso_code',
            new_name='currency_iso_code',
        ),
    ]
