# Generated by Django 3.2.4 on 2021-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_iso_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
