import uuid

from django.db import models
from django.utils import timezone

GENDER_CHOICES = (
    ('MA', 'Male'),
    ('FM', 'Female')
)

CURRENCY_CODE = [
    ('AFN', 'AFGHANISTAN'),
    ('EUR', 'ÅLAND ISLANDS'),
    ('ALL', 'ALBANIA'),
    ('DZD', 'ALGERIA'),
    ('USD', 'AMERICAN SAMOA'),
    ('EUR', 'ANDORRA'),
    ('AOA', 'ANGOLA'),
    ('XCD', 'ANGUILLA'),
    ('XCD', 'ANTIGUA AND BARBUDA'),
    ('ARS', 'ARGENTINA'),
    ('AMD', 'ARMENIA'),
    ('AWG', 'ARUBA'),
    ('AUD', 'AUSTRALIA'),
    ('EUR', 'AUSTRIA'),
    ('AZN', 'AZERBAIJAN'),
    ('BSD', 'BAHAMAS'),
    ('BHD', 'BAHRAIN'),
    ('BDT', 'BANGLADESH'),
    ('BBD', 'BARBADOS'),
    ('BYN', 'BELARUS'),
    ('EUR', 'BELGIUM'),
    ('BZD', 'BELIZE'),
    ('XOF', 'BENIN'),
    ('BMD', 'BERMUDA'),
    ('INR', 'BHUTAN'),
    ('BTN', 'BHUTAN'),
    ('BOB', 'BOLIVIA'),
    ('BAM', 'BOSNIA AND HERZEGOVINA'),
    ('BWP', 'BOTSWANA'),
    ('NOK', 'BOUVET ISLAND'),
    ('BRL', 'BRAZIL'),
    ('USD', 'BRITISH INDIAN OCEAN TERRITORY'),
    ('BND', 'BRUNEI DARUSSALAM'),
    ('BGN', 'BULGARIA'),
    ('XOF', 'BURKINA FASO'),
    ('BIF', 'BURUNDI'),
    ('CVE', 'CABO VERDE'),
    ('KHR', 'CAMBODIA'),
    ('XAF', 'CAMEROON'),
    ('CAD', 'CANADA'),
    ('KYD', 'CAYMAN ISLANDS'),
    ('XAF', 'CENTRAL AFRICAN REPUBLIC'),
    ('XAF', 'CHAD'),
    ('CLP', 'CHILE'),
    ('CLF', 'CHILE'),
    ('CNY', 'CHINA'),
    ('AUD', 'CHRISTMAS ISLAND'),
    ('AUD', 'COCOS (KEELING) ISLANDS'),
    ('COP', 'COLOMBIA'),
    ('KMF', 'COMOROS'),
    ('CDF', 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)'),
    ('XAF', 'CONGO'),
    ('NZD', 'COOK ISLANDS'),
    ('CRC', 'COSTA RICA'),
    ('XOF', "CÔTE D'IVOIRE"),
    ('HRK', 'CROATIA'),
    ('CUP', 'CUBA'),
    ('CUC', 'CUBA'),
    ('ANG', 'CURAÇAO'),
    ('EUR', 'CYPRUS'),
    ('CZK', 'CZECHIA'),
    ('DKK', 'DENMARK'),
    ('DJF', 'DJIBOUTI'),
    ('XCD', 'DOMINICA'),
    ('DOP', 'DOMINICAN REPUBLIC'),
    ('USD', 'ECUADOR'),
    ('EGP', 'EGYPT'),
    ('SVC', 'EL SALVADOR'),
    ('USD', 'EL SALVADOR'),
    ('XAF', 'EQUATORIAL GUINEA'),
    ('ERN', 'ERITREA'),
    ('EUR', 'ESTONIA'),
    ('SZL', 'ESWATINI'),
    ('ETB', 'ETHIOPIA'),
    ('EUR', 'EUROPEAN UNION'),
    ('FKP', 'FALKLAND ISLANDS'),
    ('DKK', 'FAROE ISLANDS'),
    ('FJD', 'FIJI'),
    ('EUR', 'FINLAND'),
    ('EUR', 'FRANCE'),
    ('EUR', 'FRENCH GUIANA'),
    ('XPF', 'FRENCH POLYNESIA'),
    ('EUR', 'FRENCH SOUTHERN TERRITORIES'),
    ('XAF', 'GABON'),
    ('GMD', 'GAMBIA'),
    ('GEL', 'GEORGIA'),
    ('EUR', 'GERMANY'),
    ('GHS', 'GHANA'),
    ('GIP', 'GIBRALTAR'),
    ('EUR', 'GREECE'),
    ('DKK', 'GREENLAND'),
    ('XCD', 'GRENADA'),
    ('EUR', 'GUADELOUPE'),
    ('USD', 'GUAM'),
    ('GTQ', 'GUATEMALA'),
    ('GBP', 'GUERNSEY'),
    ('GNF', 'GUINEA'),
    ('XOF', 'GUINEA-BISSAU'),
    ('GYD', 'GUYANA'),
    ('HTG', 'HAITI'),
    ('USD', 'HAITI'),
    ('AUD', 'HEARD ISLAND AND McDONALD ISLANDS'),
    ('EUR', 'HOLY SEE'),
    ('HNL', 'HONDURAS'),
    ('HKD', 'HONG KONG'),
    ('HUF', 'HUNGARY'),
    ('ISK', 'ICELAND'),
    ('INR', 'INDIA'),
    ('IDR', 'INDONESIA'),
    ('IRR', 'IRAN'),
    ('IQD', 'IRAQ'),
    ('EUR', 'IRELAND'),
    ('GBP', 'ISLE OF MAN'),
    ('ILS', 'ISRAEL'),
    ('EUR', 'ITALY'),
    ('JMD', 'JAMAICA'),
    ('JPY', 'JAPAN'),
    ('GBP', 'JERSEY'),
    ('JOD', 'JORDAN'),
    ('KZT', 'KAZAKHSTAN'),
    ('KES', 'KENYA'),
    ('AUD', 'KIRIBATI'),
    ('KPW', 'KOREA (North Korea)'),
    ('KRW', 'KOREA (South Korea)'),
    ('KWD', 'KUWAIT'),
    ('KGS', 'KYRGYZSTAN'),
    ('LAK', 'LAO PEOPLE’S DEMOCRATIC REPUBLIC'),
    ('EUR', 'LATVIA'),
    ('LBP', 'LEBANON'),
    ('LSL', 'LESOTHO'),
    ('ZAR', 'LESOTHO'),
    ('LRD', 'LIBERIA'),
    ('LYD', 'LIBYA'),
    ('CHF', 'LIECHTENSTEIN'),
    ('EUR', 'LITHUANIA'),
    ('EUR', 'LUXEMBOURG'),
    ('MOP', 'MACAO'),
    ('MKD', 'NORTH MACEDONIA'),
    ('MGA', 'MADAGASCAR'),
    ('MWK', 'MALAWI'),
    ('MYR', 'MALAYSIA'),
    ('MVR', 'MALDIVES'),
    ('XOF', 'MALI'),
    ('EUR', 'MALTA'),
    ('USD', 'MARSHALL ISLANDS'),
    ('EUR', 'MARTINIQUE'),
    ('MRU', 'MAURITANIA'),
    ('MUR', 'MAURITIUS'),
    ('EUR', 'MAYOTTE'),
    ('MXN', 'MEXICO'),
    ('USD', 'MICRONESIA'),
    ('MDL', 'MOLDOVA'),
    ('EUR', 'MONACO'),
    ('MNT', 'MONGOLIA'),
    ('EUR', 'MONTENEGRO'),
    ('XCD', 'MONTSERRAT'),
    ('MAD', 'MOROCCO'),
    ('MZN', 'MOZAMBIQUE'),
    ('MMK', 'MYANMAR'),
    ('NAD', 'NAMIBIA'),
    ('ZAR', 'NAMIBIA'),
    ('AUD', 'NAURU'),
    ('NPR', 'NEPAL'),
    ('EUR', 'NETHERLANDS'),
    ('XPF', 'NEW CALEDONIA'),
    ('NZD', 'NEW ZEALAND'),
    ('NIO', 'NICARAGUA'),
    ('XOF', 'NIGER'),
    ('NGN', 'NIGERIA'),
    ('NZD', 'NIUE'),
    ('AUD', 'NORFOLK ISLAND'),
    ('USD', 'NORTHERN MARIANA ISLANDS'),
    ('NOK', 'NORWAY'),
    ('OMR', 'OMAN'),
    ('PKR', 'PAKISTAN'),
    ('USD', 'PALAU'),
    ('PAB', 'PANAMA'),
    ('USD', 'PANAMA'),
    ('PGK', 'PAPUA NEW GUINEA'),
    ('PYG', 'PARAGUAY'),
    ('PEN', 'PERU'),
    ('PHP', 'PHILIPPINES'),
    ('NZD', 'PITCAIRN'),
    ('PLN', 'POLAND'),
    ('EUR', 'PORTUGAL'),
    ('USD', 'PUERTO RICO'),
    ('QAR', 'QATAR'),
    ('EUR', 'RÉUNION'),
    ('RON', 'ROMANIA'),
    ('RUB', 'RUSSIAN FEDERATION'),
    ('RWF', 'RWANDA'),
    ('WST', 'SAMOA'),
    ('EUR', 'SAN MARINO'),
    ('STN', 'SAO TOME AND PRINCIPE'),
    ('SAR', 'SAUDI ARABIA'),
    ('XOF', 'SENEGAL'),
    ('RSD', 'SERBIA'),
    ('SCR', 'SEYCHELLES'),
    ('SLL', 'SIERRA LEONE'),
    ('SGD', 'SINGAPORE'),
    ('EUR', 'SLOVAKIA'),
    ('EUR', 'SLOVENIA'),
    ('SBD', 'SOLOMON ISLANDS'),
    ('SOS', 'SOMALIA'),
    ('ZAR', 'SOUTH AFRICA'),
    ('SSP', 'SOUTH SUDAN'),
    ('EUR', 'SPAIN'),
    ('LKR', 'SRI LANKA'),
    ('SDG', 'SUDAN'),
    ('SRD', 'SURINAME'),
    ('SEK', 'SWEDEN'),
    ('CHF', 'SWITZERLAND'),
    ('SYP', 'SYRIAN ARAB REPUBLIC'),
    ('TWD', 'TAIWAN'),
    ('TJS', 'TAJIKISTAN'),
    ('TZS', 'TANZANIA'),
    ('THB', 'THAILAND'),
    ('USD', 'TIMOR-LESTE'),
    ('XOF', 'TOGO'),
    ('NZD', 'TOKELAU'),
    ('TOP', 'TONGA'),
    ('TTD', 'TRINIDAD AND TOBAGO'),
    ('TND', 'TUNISIA'),
    ('TRY', 'TURKEY'),
    ('TMT', 'TURKMENISTAN'),
    ('USD', 'TURKS AND CAICOS ISLANDS'),
    ('AUD', 'TUVALU'),
    ('UGX', 'UGANDA'),
    ('UAH', 'UKRAINE'),
    ('AED', 'UNITED ARAB EMIRATES'),
    ('GBP', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND'),
    ('USD', 'UNITED STATES MINOR OUTLYING ISLANDS'),
    ('USD', 'UNITED STATES OF AMERICA'),
    ('UYU', 'URUGUAY'),
    ('UZS', 'UZBEKISTAN'),
    ('VUV', 'VANUATU'),
    ('VES', 'VENEZUELA'),
    ('VND', 'VIET NAM'),
    ('USD', 'VIRGIN ISLANDS'),
    ('XPF', 'WALLIS AND FUTUNA'),
    ('MAD', 'WESTERN SAHARA'),
    ('YER', 'YEMEN'),
    ('ZMW', 'ZAMBIA'),
    ('ZWL', 'ZIMBABWE'),
    ('NGN', 'NIGERIA'),
    ('NZD', 'NIUE'),
    ('AUD', 'NORFOLK ISLAND'),
    ('USD', 'NORTHERN MARIANA ISLANDS'),
    ('NOK', 'NORWAY'),
    ('OMR', 'OMAN'),
    ('PKR', 'PAKISTAN'),
    ('USD', 'PALAU'),
    ('PAB', 'PANAMA'),
    ('USD', 'PANAMA'),
    ('PGK', 'PAPUA NEW GUINEA'),
    ('PYG', 'PARAGUAY'),
    ('PEN', 'PERU'),
    ('PHP', 'PHILIPPINES'),
    ('NZD', 'PITCAIRN'),
    ('PLN', 'POLAND'),
    ('EUR', 'PORTUGAL'),
    ('USD', 'PUERTO RICO'),
    ('QAR', 'QATAR'),
    ('EUR', 'RÉUNION'),
    ('RON', 'ROMANIA'),
    ('RUB', 'RUSSIAN FEDERATION'),
    ('RWF', 'RWANDA'),
    ('WST', 'SAMOA'),
    ('EUR', 'SAN MARINO'),
    ('STN', 'SAO TOME AND PRINCIPE'),
    ('SAR', 'SAUDI ARABIA'),
    ('XOF', 'SENEGAL'),
    ('RSD', 'SERBIA'),
    ('SCR', 'SEYCHELLES'),
    ('SLL', 'SIERRA LEONE'),
    ('SGD', 'SINGAPORE'),
    ('EUR', 'SLOVAKIA'),
    ('EUR', 'SLOVENIA'),
    ('SBD', 'SOLOMON ISLANDS'),
    ('SOS', 'SOMALIA'),
    ('ZAR', 'SOUTH AFRICA'),
    ('SSP', 'SOUTH SUDAN'),
    ('EUR', 'SPAIN'),
    ('LKR', 'SRI LANKA'),
    ('SDG', 'SUDAN'),
    ('SRD', 'SURINAME'),
    ('SEK', 'SWEDEN'),
    ('CHF', 'SWITZERLAND'),
    ('SYP', 'SYRIAN'),
    ('TWD', 'TAIWAN'),
    ('TJS', 'TAJIKISTAN'),
    ('TZS', 'TANZANIA'),
    ('THB', 'THAILAND'),
    ('XOF', 'TOGO'),
    ('NZD', 'TOKELAU'),
    ('TOP', 'TONGA'),
    ('TTD', 'TRINIDAD AND TOBAGO'),
    ('TND', 'TUNISIA'),
    ('TRY', 'TURKEY'),
    ('TMT', 'TURKMENISTAN'),
    ('USD', 'TURKS AND CAICOS ISLANDS'),
    ('AUD', 'TUVALU'),
    ('UGX', 'UGANDA'),
    ('UAH', 'UKRAINE'),
    ('AED', 'UNITED ARAB EMIRATES'),
    ('GBP', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND'),
    ('USD', 'UNITED STATES MINOR OUTLYING ISLANDS'),
    ('USD', 'UNITED STATES OF AMERICA'),
    ('UYU', 'URUGUAY'),
    ('UZS', 'UZBEKISTAN'),
    ('VUV', 'VANUATU'),
    ('VES', 'VENEZUELA'),
    ('VND', 'VIET NAM'),
    ('USD', 'VIRGIN ISLANDS'),
    ('XPF', 'WALLIS AND FUTUNA'),
    ('MAD', 'WESTERN SAHARA'),
    ('YER', 'YEMEN'),
    ('ZMW', 'ZAMBIA'),
    ('ZWL', 'ZIMBABWE')
]

class AbstractBase(models.Model):
    """Base class for all models that belong to pesa_exchange application."""

    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    created = models.DateTimeField(db_index=True, default=timezone.now)
    created_by = models.UUIDField(null=True, blank=True)
    updated = models.DateTimeField(db_index=True, default=timezone.now)
    updated_by = models.UUIDField(null=True, blank=True)

    def preserve_created_and_created_by(self):
        """Ensure that created and created_by are not changed during updates."""
        try:
            original = self.__class__.objects.get(pk=self.pk)
            self.created = original.created
            self.created_by = original.created_by
        except self.__class__.DoesNotExist:
            pass

    def save(self, *args, **kwargs):
        """Ensure validations are run and updated/created preserved."""
        self.updated = timezone.now()
        self.full_clean(exclude=None)
        self.preserve_created_and_created_by()
        super(AbstractBase, self).save(*args, **kwargs)

    class Meta:
        """Define a default least recently used ordering."""

        abstract = True
        ordering = ('-updated', '-created')
