# Generated by Django 3.2.4 on 2021-06-20 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_password_expire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='change_pass_at_next_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_system_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_password_change',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
