# Generated by Django 3.2.4 on 2021-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MA', 'Male'), ('FM', 'Female')], max_length=2, null=True),
        ),
    ]
